version: "3.1"

services:

  db_server:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: productdb
      MYSQL_ROOT_PASSWORD: fooda
    ports:
      - 3421:3306

  db_admin:
    image: adminer:4.8.1-standalone
    restart: always
    depends_on:
      - db_server
    ports:
      - 9121:8080

  backend:
    image: yilmazchef/fooda-backend-product:latest
    depends_on:
      - db_server
      - db_admin
    links:
      - db_server:db_server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_server:3306/productdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSOWRD: fooda
    ports:
      - 8121:8080