server:
  port: ${PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        search:
          backend:
            directory:
              type: local-heap
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:fooda}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}
      roles: ${SPRING_SECURITY_ROLES}

  application:
    name: fooda-backend-product

  jackson:
    serialization:
      indent-output: true
    default-property-inclusion: non-null

logging:
  level:
    org.zalando.logbook: TRACE

fooda:
  backend:
    store:
      url: http://localhost:8082/api/v1/store
    media:
      url: http://localhost:8083/api/v1/media
